### ISSUE TITLE
Bugs review lần 1

### ISSUE THREAD

**Issue by buutv** [IDS-V-Tuanlt/UserManagement#1]
@IDS-V-Tuanlt 
Em check lại dưới đây, 
1. Chưa format code theo chuẩn PSR-2 bên dưới.
http://vn-redmine.ids.co.jp/redmine/projects/ids_common_issues/wiki/Common_Coding_Rule
2. Các functions nào sử dụng thì để lại, function nào k0 dùng thì delete.
3. Hiện tạo thì thấy code của ProductController viết chưa đúng theo yêu cầu ban đầu.
4. Phần view chưa sử dụng master page (app.blade.php) chung cho các trang.
5. CSS, JS cũng chưa dùng chung.
6. ..................................

**Comment by IDS-V-Tuanlt** [comment]
Done
